secrets:
  api_key_secret:
    file: ./secrets/api_key.txt

x-common-backend: &common-backend
  build: ./backend
  restart: unless-stopped
  networks:
      backend-network:
        aliases:
          - backend
  expose:
      - "8081"
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
    interval: 5s
    timeout: 3s
    retries: 3

x-common-frontend: &common-frontend
  build: ./frontend
  restart: unless-stopped
  networks:
      frontend-network:
        aliases:
          - frontend
  expose:
      - "80"
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/momo-store/"]
    interval: 10s
    timeout: 5s
    retries: 3

x-common-proxy: &common-proxy
  image: nginxinc/nginx-unprivileged:1.29.8-alpine
  restart: unless-stopped
  container_name: proxy_app
  ports: ["80:80"]
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  read_only: true
  tmpfs: [/var/cache/nginx, /var/run, /tmp]
  cap_drop: [ALL]
  cap_add: [NET_BIND_SERVICE]
  networks: [frontend-network, backend-network]
  deploy:
    resources: { limits: { cpus: '0.2', memory: 128M } }

services:
  proxy-prod:
    <<: *common-proxy
    profiles: ["prod"]
    depends_on:
      frontend-prod: { condition: service_healthy }
      backend-prod: { condition: service_healthy }

  backend-prod:
    <<: *common-backend
    image: ${DOCKER_REGISTRY}/docker-project-backend:${TAG:-latest}
    profiles: ["prod"]
    read_only: true 
    tmpfs: [/tmp]
    volumes: [backend-logs:/app/logs]
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
      resources:
        limits:
          cpus: '${FE_CPU:-0.3}'
          memory: ${FE_MEM:-128M}
    secrets: [api_key_secret]
    environment:
      - API_KEY_FILE=/run/secrets/api_key_secret

  frontend-prod:
    <<: *common-frontend
    image: ${DOCKER_REGISTRY}/docker-project-frontend:${TAG:-latest}
    profiles: ["prod"]
    read_only: true
    tmpfs: [/var/cache/nginx, /var/run, /tmp]
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    deploy:
      replicas: ${FRONTEND_REPLICAS:-1}
      resources:
        limits:
          cpus: '${FE_CPU:-0.3}'
          memory: ${FE_MEM:-128M}

  #DEV
  proxy-dev:
    <<: *common-proxy
    profiles: ["dev"]
    depends_on:
      frontend-dev: { condition: service_healthy }
      backend-dev: { condition: service_healthy }
    networks: [app-network]

  backend-dev:
    <<: *common-backend
    profiles: ["dev"]
    container_name: backend_dev
    volumes:
      - ./backend:/app
    read_only: false

  frontend-dev:
    <<: *common-frontend
    profiles: ["dev"]
    container_name: frontend_dev
    volumes:
      - ./frontend:/app
    read_only: false

networks:
  frontend-network:
  backend-network:

volumes:
  backend-logs: