upstream backend_pool {
    server backend:8081;
}

upstream frontend_pool {
    server frontend:80;
}

server {
    listen 80;
    server_name localhost;

    location ~ ^/momo-store/(products|categories|cart|login|api) {
        rewrite ^/momo-store/(.*)$ /$1 break;
        proxy_pass http://backend_pool;
        proxy_set_header Host $host;
    }

    location /auth/ {
        rewrite ^/auth/(.*)$ /$1 break;
        proxy_pass http://backend_pool;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://frontend_pool;
        proxy_set_header Host $host;
    }
}